# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newfriends.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newfriends(object):
    def setupUi(self, newfriends):
        newfriends.setObjectName("newfriends")
        newfriends.resize(200, 200)
        newfriends.setStyleSheet("QWidget{\n"
"    rgb(255, 255, 255)\n"
"}")
        self.frame = QtWidgets.QFrame(newfriends)
        self.frame.setGeometry(QtCore.QRect(0, 0, 201, 201))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color:rgb(225, 225, 225)\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 10, 141, 31))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(10, 150, 75, 23))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color:rgb(0, 194, 0)\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 150, 75, 23))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"\n"
"    background-color:rgb(230, 0, 0)\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 151, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 101, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(newfriends)
        QtCore.QMetaObject.connectSlotsByName(newfriends)

    def retranslateUi(self, newfriends):
        self.setWindowTitle("新的好友申请！")   # 设置窗口名
        _translate = QtCore.QCoreApplication.translate
        newfriends.setWindowTitle(_translate("newfriends", "Form"))
        self.label.setText(_translate("newfriends", "该用户向您发送好友申请！"))
        self.pushButton.setText(_translate("newfriends", "接受√"))
        self.pushButton_2.setText(_translate("newfriends", "拒绝×"))
        self.label_2.setText(_translate("newfriends", "Email: 1257820962@qq.com"))
        self.label_3.setText(_translate("newfriends", "用户名：张宇轩"))
